Add setting to ignore collisions
Nexela/PickerDollies pull request #11
Opened 2022-02-05 21:39 UTC by sparr

This per-user setting disables the check for entities colliding when moving. It is cheaty and dangerous if you leave entities overlapping, but very helpful when trying to rearrange already-packed-together entities. I found myself needing this to swap the position of two train stations with complex circuit connections that I didn't want to re-connect by hand.

2022-02-06 02:00 UTC, Nexela requested changes
I am willing to accept this with a modification. 
A global setting as well as the user setting to allow for servers to keep it disabled.

2022-02-06 02:06 UTC, Nexela commented
See #12 if you also want to tackle that.

2022-02-06 02:22 UTC, sparr commented
Should the user get any feedback, or should their setting just silently not work if the global is set?

2022-02-06 02:43 UTC, Nexela commented
Silent is fine as long as the description states it only works if enabled on the server.

2022-02-06 04:21 UTC, sparr commented
Should the global setting default to allow or forbid?

2022-02-06 04:22 UTC, Nexela commented
Forbid

On Sat, Feb 5, 2022, 11:21 PM sparr ***@***.***> wrote:

> Should the global setting default to allow or forbid?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Nexela/PickerDollies/pull/11#issuecomment-1030749206>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADKTFYHGX7SLU6NHACZDXW3UZXZM7ANCNFSM5NUPCM2Q>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-03-05 20:54 UTC, Nexela approved these changes

2022-03-05 20:54 UTC, merged